# Generated by Django 5.2.1 on 2025-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_mediatype_streamplatform_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
