# Generated by Django 5.2.1 on 2025-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_mediatype_media_type_alter_mediatype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
